# Generated by Django 4.0.6 on 2022-08-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_montauk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='subtítulo',
            new_name='subtitulo',
        ),
    ]
