# Generated by Django 4.0.6 on 2022-08-10 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_montauk', '0004_delete_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='imagen',
            new_name='imagen_blog',
        ),
    ]
