# Generated by Django 4.0.6 on 2022-08-10 21:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_montauk', '0005_rename_imagen_blog_imagen_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
